version: 2
updates:
  - package-ecosystem: cargo
    directory: /backend
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /extension
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"
